version: "3.7"
services:
  api_service:
    build: .
    container_name: spring_container
    restart: always
    ports:
      - 8081:8081
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}

  ###   depends_on:
  ###      - mysqldb
  ###    volumes:
  ###     - .m2:/root/.m2
##networks:
##  springapimysql-net:
###
